#!/bin/bash

programName=JErgometer
svnRepo=https://jergometer.org/svn/jergometer

version=$1
prefix=$programName-$version

# tag this release
#svn copy . $svnRepo/tags/$version -m "released version $version"

mkdir -p dist/releases

cd dist/${programName}_prepare
zsh ../../scripts/create_versions_xml >versions.xml
cd ..

rm -Rf $programName
mv ${programName}_prepare $programName

# pack
zip -r $prefix.zip $programName
tar -czf $prefix.tar.gz $programName

mv $prefix.* releases/

# create symbolic links (last.*)
cd releases
for ext in zip tar.gz; do
	[ -e $programName-latest.$ext ] && rm $programName-latest.$ext
	ln -s $prefix.$ext $programName-latest.$ext
done

cd ../..
