#!/bin/zsh

setopt EXTENDED_GLOB
# setopt KSH_GLOB

echo '<file>'
for file in `print **/(*~versions.xml)(.)`; do
	md5=`md5sum $file | cut -d " " -f 1`
	len=`du --apparent-size -b $file | cut -f 1`
	echo "\t<file name=\"$file\" version=\"$md5\" length=\"$len\"/>"
done
echo '</files>'
