#!/bin/bash

programName=JErgometer

version=$1
prefix=$programName-$version

# tag this release
git tag -a "v$version" -m "version $version"
git push --tags

mkdir -p dist/releases

cd dist/${programName}_prepare
zsh ../../scripts/create_versions_xml >versions.xml
cd ..

rm -Rf $programName
mv ${programName}_prepare $programName

# pack
zip -r $prefix.zip $programName
tar -czf $prefix.tar.gz $programName

mv $prefix.* releases/

# create symbolic links (last.*)
#cd releases
#for ext in zip tar.gz; do
#	[ -e $programName-latest.$ext ] && rm $programName-latest.$ext
#	ln -s $prefix.$ext $programName-latest.$ext
#done

# create new redirects for latest versions
cd releases
echo 'Redirect /releases/$programName-latest.tar.gz /releases/$prefix.tar.gz
Redirect /releases/$programName-latest.zip /releases/$prefix.zip
' >.htaccess

cd ../..
